baseURL: "/"
languageCode: fr-fr
title: partage de connaissances de bachrc
theme: "PaperMod"
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: blog.dessert.coffee
  description: "ici on apprend des trucs"
  keywords: [bachrc, craft, blog, tdd]
  author: bachrc
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2 January 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  profileMode:
    enabled: true
    title: bachrc
    subtitle: c'est moi
    imageUrl: "moibg.jpg"
    imageTitle: Yohann Bacha
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Articles
        url: posts
      - name: Tags
        url: tags

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    #favicon16x16: "<link / abs url>"
    favicon32x32: "favicon.ico"
    apple_touch_icon: "cup.png"
    safari_pinned_tab: "cup.png"

  label:
    url: aaaaaaa
    text: "dessert.coffee"
    icon: /cup.svg
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "centre de formation bachrc"
    Content: >
      Bienvenue dans ce centre de formation.

      - Des fois je fais des recherches, je les sérialise ici.

      - Principalement du dev, mais pas forcément que ça. Abonne-toi au flux RSS. Mets la cloche.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/_bachrc"
    - name: github
      url: "https://github.com/bachrc"
    - name: linkedin
      url: "https://linkedin.com/in/yohannbacha"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/4618966/bachrc"
    - name: email
      url: "mailto:bachrc@dessert.coffee"
    - name: RsS
      url: "index.xml"

#  analytics:
#    google:
#      SiteVerificationTag: "XYZabc"
#    bing:
#      SiteVerificationTag: "XYZabc"
#    yandex:
#      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/bachrc/blog-dessert-coffee/content"
    Text: "Suggérer un changement" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: blog
      url: /posts
      weight: 10
    - identifier: categories
      name: categories
      url: /categories
      weight: 20
    - identifier: tags
      name: tags
      url: /tags
      weight: 30
    - identifier: about
      name: à propos
      url: /about
      weight: 40

taxonomies:
  category: categories
  tag: tags
  series: series
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
