version: "3"
services:
  server:
    image: klakegg/hugo:0.83.1
    hostname: blog
    command: server --renderToDisk --baseURL=https://dessert.coffee --appendPort=false
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    networks:
      - proxied-apps


networks:
  proxied-apps:
    external: true
