version: "3"
services:
  server:
    image: klakegg/hugo:0.83.1
    command: server --renderToDisk --baseURL=https://dessert.coffee --appendPort=false
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    networks:
      proxied_apps:
        - ipv4_address: 172.19.0.4

networks:
  proxied_apps:
    external: true
